#remote_theme : jekyllup/jekyll-theme-massively@master
# remote-theme : h01000110/windows-95@master
# plugins:
# - jekyll-remote-theme
  
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: PQuod/simply-cyan-theme

permissions:
  id-token: write
  contents: read

title : Cuisine Classifier
description :  Can identify 20 popular Cuisines from all around the world 

author:
  name: Arian Rahman